version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '27081:80'
    container_name: wxcloud_ynrl-koa
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=ynrl-koa
      - role=container
    environment:
      - MYSQL_USERNAME=
      - MYSQL_PASSWORD=
      - MYSQL_ADDRESS=
      - MYSQL_USERNAME=mactest
      - MYSQL_PASSWORD=Wcjsnbb123
      - MYSQL_ADDRESS=sh-cynosdbmysql-grp-98qn6nua.sql.tencentcdb.com:23983
networks:
  default:
    external:
      name: wxcb0
